[package]
name = "hoomd-spatial"
categories.workspace = true
description = "Infrastructure for efficient computation of neighbors using spatial data structures."
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme = "hoomd-spatial/README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
hoomd-vector.workspace = true

[dev-dependencies]
rstest.workspace = true
