[package]
name = "hoomd-md"
categories.workspace = true
description = "Simulate molecular dynamics in systems of particles."
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme = "hoomd-md/README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
hoomd-linear-algebra.workspace = true
hoomd-interaction.workspace = true
hoomd-microstate.workspace = true
hoomd-utility.workspace = true
hoomd-vector.workspace = true
hoomd-simulation.workspace = true
rand.workspace = true
rand_distr.workspace = true
bevy_egui.workspace = true

[dev-dependencies]
hoomd-geometry.workspace = true
hoomd-bevy.workspace = true
bevy = { workspace = true }
approxim.workspace = true
divan.workspace = true
rstest.workspace = true
rand.workspace = true
ratatui = "0.28.0"
anyhow = "1.0.98"
