[package]
name = "threefry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
num-traits = "0.2.19"
cipher = { version = "0.5.0-rc.1", features = ["stream-wrapper"] }
rand_core = "0.9.0"
# rand_core.workspace = true
rand.workspace = true
wide = "0.7.33"

[lints]
workspace = true
