words = [
    "dyn",
    "hoomd",
    "hypersphere",
    "hyperspheres",
    "hypervolume",
    "macrostate",
    "microstate",
    "newtype",
    "orientable",
    "polytope",
    "polytopes",
    "shader",
    "sps",
    "versor",
    "winit",
    "xenocollide",
]
