words = [
    "binaryen",
    "bindgen",
    "dyn",
    "hoomd",
    "hypersphere",
    "hyperspheres",
    "hypervolume",
    "katex",
    "lennard",
    "macrostate",
    "mdbook",
    "micromamba",
    "microstate",
    "microstates",
    "monomorphization",
    "newtype",
    "orientable",
    "polytope",
    "polytopes",
    "rustup",
    "shader",
    "sps",
    "versor",
    "winit",
    "wsl",
    "xenocollide",
]
