version: 2
build:
  os: "ubuntu-24.04"
  tools:
    rust: "1.91"
  commands:
    # Install cargo binstall
    - mkdir -p "${PATH%%:*}"
    - curl -sSL "https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-gnu.tgz" | tar -xvz --directory "${PATH%%:*}"
    # Install mdbook
    - cargo binstall mdbook@0.4.52 mdbook-alerts@0.8.0 --no-confirm --disable-strategies=compile --disable-telemetry --install-path "${PATH%%:*}"
    - curl -sSL "https://github.com/lzanini/mdbook-katex/releases/download/0.10.0-alpha-binaries/mdbook-katex-v0.10.0-alpha-x86_64-unknown-linux-gnu.tar.gz" | tar -xvz --directory "${PATH%%:*}"
    # Install wasm toolchain with bindgen matching the version in the lockfile
    - rustup target install wasm32-unknown-unknown
    - cargo info wasm-bindgen -q
    - cargo binstall wasm-bindgen-cli@`cargo info wasm-bindgen -q | grep "^version:" | cut -f 2 -d " "` --no-confirm --disable-strategies=compile --disable-telemetry --install-path "${PATH%%:*}"
    - curl -sSL "https://github.com/WebAssembly/binaryen/releases/download/version_123/binaryen-version_123-x86_64-linux.tar.gz" | tar -xvz --strip-components 2 --directory "${PATH%%:*}"
    - ls "${PATH%%:*}"
    # Build the WASM examples
    - cargo run --locked -p build-wasm-doc-examples -- --reduce-size
    # Build the book
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - echo "site-url = \"/$READTHEDOCS_LANGUAGE/$READTHEDOCS_VERSION/\"" >> doc/book.toml
    - mdbook build doc --dest-dir=$READTHEDOCS_OUTPUT/html
    # Build the API reference
    - mkdir -p $READTHEDOCS_OUTPUT/html/api
    - RUSTDOCFLAGS="--html-in-header katex.html" cargo doc --locked --workspace --all-features --exclude benchmarks --exclude hoomd-examples --lib --no-deps
    - mv target/doc/* $READTHEDOCS_OUTPUT/html/api
    # List the output files
    - ls -lR $READTHEDOCS_OUTPUT/html
