[package]
name = "hoomd-utility"
categories.workspace = true
description = "Commonly used utility types and methods."
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
parquet.workspace = true
parquet_derive.workspace = true
thiserror.workspace = true
serde.workspace = true

[dev-dependencies]
anyhow.workspace = true
assert2.workspace = true
tempfile.workspace = true
