[package]
name = "hoomd-mc"
categories.workspace = true
description = "Perfom Monte Carlo simulations on systems of particles."
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme = "hoomd-mc/README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
hoomd-interaction = { path = "../hoomd-interaction" }
hoomd-microstate = { path = "../hoomd-microstate" }
hoomd-random = { path = "../hoomd-random" }
hoomd-vector = { path = "../hoomd-vector" }
rand = "0.9.0"

[dev-dependencies]
approx = "0.5.1"
divan = "0.1.17"
rstest = "0.25.0"
rand = "0.9.0"
