[package]
name = "hoomd-mc"
categories.workspace = true
description = "Perfom Monte Carlo simulations on systems of particles."
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme = "hoomd-mc/README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
hoomd-interaction.workspace = true
hoomd-microstate.workspace = true
hoomd-utility.workspace = true
hoomd-vector.workspace = true
rand.workspace = true

[dev-dependencies]
anyhow.workspace = true
approx.workspace = true
divan.workspace = true
rstest.workspace = true
rand.workspace = true
bevy.workspace = true
bevy_diagnostic.workspace = true ## TODO: move to hoomd_bevy
ratatui = "0.28.0"
