[package]
name = "hoomd-model"
categories.workspace = true
description = "Models describe how systems behave."
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme = "hoomd-model/README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
hoomd-interaction = { path = "../hoomd-interaction" }
hoomd-microstate = { path = "../hoomd-microstate" }
hoomd-vector = { path = "../hoomd-vector" }

[dev-dependencies]
approx = "0.5.1"
rstest = "0.25.0"
rand = "0.9.0"
