[package]
name = "hoomd-manifold"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
thiserror.workspace = true
rand.workspace = true
hoomd-utility.workspace = true
hoomd-vector.workspace = true
libm = "0.2.11"
num = "0.4.3"

[dev-dependencies]
approx.workspace = true
divan.workspace = true
paste = "1.0.15"
rstest.workspace = true

[lints]
workspace = true

[[bench]]
name = "minkowski"
harness = false 

[[bench]]
name = "biquaternion"
harness = false 

[[bench]]
name = "hyperbolic_angle"
harness = false 