[package]
name = "hoomd-rand"
description = "Performant random number generators, designed and tested for HPC."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex.html" ]

[dependencies]
clap.workspace = true
rand.workspace = true
serde.workspace = true

[lints]
workspace = true

[[bin]]
name = "catrng"
path = "bin/catrng.rs"

[features]
default = []
extras = []

[dev-dependencies]
assert2.workspace = true
approxim.workspace = true
chacha20 = { version = "=0.10.0", default-features = false, features = ["rng"]}
divan.workspace = true
rand_sfc.workspace = true
rstest.workspace = true

[[bench]]
name = "bench"
harness = false
