[package]
name = "hoomd-rand"
description = "Performant random number generators, designed and tested for HPC."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
rand.workspace = true
clap.workspace = true

[lints]
workspace = true

[[bin]]
name = "catrng"
path = "bin/catrng.rs"

[features]
default = []
extras = []

[dev-dependencies]
approxim.workspace = true
rstest.workspace = true
divan.workspace = true
chacha20 = { version = "=0.10.0-rc.0", default-features = false, features = ["rng"]}

[[bench]]
name = "bench"
harness = false
required-features = ["extras"]
