[package]
name = "hoomd-order"
description = "Order parameter and analysis library."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
thiserror.workspace = true
hoomd-geometry.workspace = true
hoomd-interaction.workspace = true
hoomd-manifold.workspace = true
hoomd-mc.workspace = true
hoomd-microstate.workspace = true
hoomd-meshless-voronoi.workspace = true
hoomd-utility.workspace = true
hoomd-vector.workspace = true
rand.workspace = true
libm = "0.2.11"
num = "0.4.3"
ndarray = "0.16.1"
ahash = "0.8"
document-features = "0.2"
glam = "0.27"
ibig = {  version = "0.3", optional = true, default-features = false }
num-bigint = { version = "0.4", optional = true }
num_enum = { version = "0.7.2", default-features = false }
rayon = { version = "1", optional = true }
rstar = "0.12"

[features]
default = ["ibig", "rayon"]

[dev-dependencies]
approx.workspace = true
divan.workspace = true
paste = "1.0.15"
rstest.workspace = true
ratatui = "0.28.0"
float-cmp = "0.9"

[lints]
workspace = true
