[package]
name = "hoomd-order"
description = "Order parameters."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hoomd-linear-algebra.workspace = true
hoomd-vector.workspace = true
thiserror.workspace = true

[dev-dependencies]
approx.workspace = true
rstest.workspace = true

[lints]
workspace = true
