[package]
name = "hoomd-vector"
categories.workspace = true
description = "Vector and quaternion math library."
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
rand.workspace = true
rand_distr.workspace = true
thiserror.workspace = true
hoomd-linear-algebra.workspace = true
hoomd-utility.workspace = true
approxim.workspace = true

[dev-dependencies]
divan.workspace = true
paste.workspace = true
rand_distr = "0.5.1"
rstest.workspace = true

[[bench]]
name = "cartesian"
harness = false

[[bench]]
name = "angle"
harness = false

[[bench]]
name = "quaternion"
harness = false
