[package]
name = "hoomd-vector"
categories.workspace = true
description = "Vector and quaternion math library."
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[features]
approx = ["dep:approx"]

[dependencies]
rand.workspace = true
thiserror.workspace = true
hoomd-linalg.workspace = true
hoomd-utility.workspace = true
approx = { optional = true, workspace = true }

[dev-dependencies]
approx.workspace = true
divan.workspace = true
paste = "=1.0.15"
rstest.workspace = true

[[bench]]
name = "cartesian"
harness = false

[[bench]]
name = "angle"
harness = false

[[bench]]
name = "quaternion"
harness = false
