// Copyright (c) 2024-2025 The Regents of the University of Michigan.
// Part of hoomd-rs, released under the BSD 3-Clause License.
//! # ChIMES Potential Builder
//!
//! This module provides the [`ChimesBuilder`] utility to parse standard ChIMES
//! parameter files (as generated by ChIMES-LSQ) and assemble them into
//! potential functions for HOOMD-rs.
use crate::{
    potential::{
        ChimesChebyshevExpansion, ChimesPenalty, ChimesSmoothing, ChimesTransformation,
        ChimesTwobPotential, CubicSmooth, TersoffSmooth,
    },
    transformation::{DirectTransformation, InverseTransformation, MorseTransformation},
};
use hoomd_interaction::{PairwiseCutoff, pairwise::Isotropic};
use std::{collections::HashMap, error::Error, fmt, fs, iter::Peekable};

/// Errors encountered during the parsing or assembly of ChIMES potentials.
#[derive(Debug)]
pub enum ChimesError {
    /// The file structure does not match the ChIMES specification.
    InvalidFormat(String),
    /// Error during the mathematical assembly of the potential.
    Construction(String),
    /// The file ended before all expected parameters were read.
    UnexpectedEof(String),
}

impl fmt::Display for ChimesError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidFormat(m) => write!(f, "Invalid Format: {m}"),
            Self::Construction(m) => write!(f, "Potential Construction Error: {m}"),
            Self::UnexpectedEof(m) => write!(f, "Unexpected end of file: {m}"),
        }
    }
}

impl Error for ChimesError {}

/// Physical properties and energy offsets for a specific particle type.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct ParticleTypeData {
    /// The name of particle.
    pub name: String,
    /// The mass of particle.
    pub mass: f64,
    /// The single particle energy term.
    pub energy_offset: f64,
}

/// Metadata describing a pairwise interaction between two particle types.
#[derive(Clone, Debug, PartialEq)]
pub struct PairTypeData {
    /// The name of the first particle in the pair.
    pub type1: String,
    /// The name of the second particle in the pair.
    pub type2: String,
    /// The inner cutoff.
    pub r_in: f64,
    /// The outer cutoff.
    pub r_out: f64,
    /// The morse lambda for the [`MorseTransformation`].
    pub morse_lambda: Option<f64>,
    /// The coefficient for the [`ChimesChebyshevExpansion`].
    pub coeff: Vec<f64>,
}

/// Metadata describing a three-body interaction within triplets.
#[derive(Clone, Debug, PartialEq)]
pub struct TripletTypeData {
    /// The name of the first pair in the triplet.
    pub pair1: String,
    /// The name of the second pair in the triplet.
    pub pair2: String,
    /// The name of the third pair in the triplet.
    pub pair3: String,
    /// The inner cutoff of the `pair1`.
    pub r_in1: f64,
    /// The inner cutoff of the `pair2`.
    pub r_in2: f64,
    /// The inner cutoff of the `pair3`.
    pub r_in3: f64,
    /// The outer cutoff of the `pair1`.
    pub r_out1: f64,
    /// The outer cutoff of the `pair2`.
    pub r_out2: f64,
    /// The outer cutoff of the `pair3`.
    pub r_out3: f64,
    /// The powers of the Chebyshev polynomial products of the triplet.
    pub powers: Vec<Vec<usize>>,
    /// The coefficient of the Chebyshev polynomial products of the triplet.
    pub coeff: Vec<f64>,
}

/// Enum to encapsulate different `ChIMES` many-body cutoff styles.
#[derive(Debug)]
enum TripletCutType {
    None,
    All,
    Specific,
}

/// Builder for constructing `ChIMES` potential from
/// the `ChIMES` parameter file.
///
/// Given a known maximum two-body Chebyshev polynomial
/// orders `N`, [`ChimesBuilder`] can be used to parse the
/// potential parameter in the `ChIMES` parameter TXT file,
/// as described in the Generating a `ChIMES` model
/// writen in the [ChIMES-LSQ].
///
/// The [`ChimesBuilder::parse`] function perform the TXT file parsing
/// given a `file_path`, pointing to the TXT file. The
/// current implementation only parse out the two-body
/// potential component.
///
/// Given a valid `pair_idx`, representing one of
/// the particle pair type recognized by [`ChimesBuilder`] during
/// the excution of [`ChimesBuilder::parse`].
/// The [`ChimesBuilder::get_twob_chimes_potential`] assemble the complete
/// `ChIMES` two-body potential functional, wrapped in [`PairwiseCutoff`]
/// , and return it.
/// 
/// # Notes
///
/// The current implementation does parse out the three-body parameters
/// and store it in the [`ChimesBuilder`], but it does not provide the
/// construction implementaion of three-body potential functional.
///
/// The current implementation ignores the four-body parameters.
///
/// [ChIMES-LSQ]: <https://chimes-lsq.readthedocs.io/en/latest/lsq_input_file.html>
///
///
/// # Example
/// ```
/// use hoomd_chimes::builder::ChimesBuilder;
///
/// // Maximum two-body order is 12 for the example parameter file.
/// const N: usize = 12;
/// // No three-body interaction.
/// const M: usize = 0;
///
/// let mut file_path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
/// file_path.push("test-data");
/// file_path.push("C-twobody.txt");
///
/// let chimes_builder =
///     ChimesBuilder::<N, M>::parse(file_path.to_str().expect("Path contains invalid symbols"))
///         .expect("Failed to parse parameter file");
/// let chimes_fn = chimes_builder.get_twob_chimes_potential(0).expect("Error assemling ChIMES potential");
/// assert_eq!(chimes_fn.0.interaction.type1, String::from("C"));
/// ```
#[derive(Clone, Debug, PartialEq)]
pub struct ChimesBuilder<const N: usize, const M: usize> {
    /// A [`Vec`] of Chebyshev polynomial orders for
    /// two-, three-, and four-body, respectively.
    pub poly_order: Vec<usize>,
    /// Number of atom types.
    pub num_atom_types: usize,
    /// A [`Vec`] stores parameters of each particle type
    /// as [`Vec<ParticleTypeData>`]. Please see [`ParticleTypeData`].
    pub type_data: Vec<ParticleTypeData>,
    /// Number of pair types.
    pub num_pair_types: usize,
    /// Distance transformation style, assuming the same for all pair types.
    pub xform_style: String,
    /// A [`Vec`] stores parameters of each pair type
    /// as [`Vec<PairTypeData>`]. Please see [`PairTypeData`].
    pub pair_data: Vec<PairTypeData>,
    /// A tuple of `ChIMES` smoothing type and parameter,
    /// assuming the same for all pair types.
    /// See [`ChimesSmoothing`].
    pub fcut: (String, Option<f64>),
    /// A [`Vec`] contains indexes of
    /// pair types slow mapping.
    pub pair_idx_slow_map: Vec<usize>,
    /// A [`Vec`] contains string of
    /// pair types for the corresponding
    /// `pair_idx_slow_map`.
    pub pair_type_slow_map: Vec<String>,
    /// A [`Vec`] contains indexes of
    /// pair types fast mapping.
    pub pair_idx_fast_map: Vec<usize>,
    /// A [`Vec`] contains string of
    /// pair types for the corresponding
    /// `pair_idx_fast_map`.
    pub pair_type_fast_map: Vec<String>,
    /// The smooth kick-in distance of [`ChimesPenalty`].
    pub penalty_dist: f64,
    /// The penalty strength of [`ChimesPenalty`].
    pub penalty_scaling: f64,
    /// A [`Vec`] stores parameters of each pair type
    /// as [`Vec<TripletTypeData>`]. Please see [`TripletTypeData`].
    pub triplet_data: Vec<TripletTypeData>,
    /// A [`Vec`] contains string of
    /// triplet types for the corresponding
    /// `pair_idx_slow_map`.
    pub triplet_type_slow_map: Vec<String>,
    /// A [`Vec`] contains indexes of
    /// triplet types slow mapping.
    pub triplet_idx_slow_map: Vec<usize>,
    /// A [`Vec`] contains indexes of
    /// pair types slow mapping.
    pub triplet_idx_fast_map: Vec<usize>,
}

impl<const N: usize, const M: usize> Default for ChimesBuilder<N, M> {
    fn default() -> Self {
        Self {
            poly_order: Vec::new(),
            num_atom_types: 0,
            type_data: Vec::new(),
            num_pair_types: 0,
            pair_data: Vec::new(),
            pair_idx_slow_map: Vec::new(),
            pair_type_slow_map: Vec::new(),
            pair_idx_fast_map: Vec::new(),
            pair_type_fast_map: Vec::new(),
            xform_style: String::from("None"),
            fcut: (String::from("None"), None),
            penalty_dist: 0.01,
            penalty_scaling: 1e+4,
            triplet_data: Vec::new(),
            triplet_idx_slow_map: Vec::new(),
            triplet_type_slow_map: Vec::new(),
            triplet_idx_fast_map: Vec::new(),
        }
    }
}

impl<const N: usize, const M: usize> ChimesBuilder<N, M> {
    /// parse the `ChIMES` parameter file given the file path.
    ///
    ///
    /// # Errors
    ///
    /// Will return `Err` if the parser
    /// cannot read the parameter file .
    ///
    /// Will return `Err` if `N` does not
    /// match the two-body order read in the
    /// parameter file.
    #[inline]
    pub fn parse(file_path: &str) -> Result<Self, ChimesError> {
        let content = fs::read_to_string(file_path).map_err(|e| {
            ChimesError::UnexpectedEof(format!("Error reading the parameter file: {e}"))
        })?;
        let mut lines = content
            .lines()
            .map(str::trim)
            .filter(|line| !line.is_empty() && !line.starts_with('!') && !line.starts_with("##"))
            .peekable();

        let mut atom_count = 0;
        let mut pair_count = 0;

        let mut poly_order = Vec::new();
        let mut type_data = Vec::new();
        let mut pair_data = Vec::new();
        let mut xform_style = String::new();
        let mut fcut = (String::new(), None);
        let mut penalty_dist = 0.01;
        let mut penalty_scaling = 1e+4;
        let mut pair_idx_slow_map = Vec::new();
        let mut pair_type_slow_map = Vec::new();

        let mut triplet_special_r_in = Vec::new();
        let mut triplet_special_r_in_pair_type = Vec::new();
        let mut triplet_special_r_in_status = TripletCutType::None;
        let mut triplet_special_r_out = Vec::new();
        let mut triplet_special_r_out_pair_type = Vec::new();
        let mut triplet_special_r_out_status = TripletCutType::None;
        let mut triplet_data = Vec::new();
        let mut triplet_idx_slow_map = Vec::new();
        let mut triplet_type_slow_map = Vec::new();
        let mut triplet_idx_fast_map = Vec::new();

        while let Some(line) = lines.next() {
            match line {
                l if l.starts_with("PAIRTYP:") => {
                    let pairtyp = Self::parse_i32_vec(l.trim_start_matches("PAIRTYP: CHEBYSHEV "))?;
                    if pairtyp.is_empty() || pairtyp[0] as usize != N {
                        return Err(ChimesError::InvalidFormat(format!(
                            "Expected two-body order {N}"
                        ))
                        .into());
                    }
                    poly_order.push(pairtyp[0] as usize);

                    if pairtyp.len() >= 4 {
                        if pairtyp[1] as usize != M {
                            return Err(ChimesError::InvalidFormat(format!(
                                "Expected three-body order {M}"
                            ))
                            .into());
                        }
                        poly_order.push(pairtyp[1] as usize);
                    }

                    if pairtyp.len() >= 5 {
                        poly_order.push(pairtyp[2] as usize);
                    }
                }

                l if l.starts_with("ATOM TYPES:") => {
                    atom_count = l
                        .trim_start_matches("ATOM TYPES: ")
                        .parse::<usize>()
                        .map_err(|e| {
                            ChimesError::InvalidFormat(format!(
                                "Error parsing the number of particle types: {e}"
                            ))
                        })?;
                    type_data = vec![ParticleTypeData::default(); atom_count];
                }

                l if l.starts_with("# TYPEIDX #") => {
                    for i in 0..atom_count {
                        let row = lines.next().ok_or(ChimesError::UnexpectedEof(
                            "Do not find atom type information, such as mass".into(),
                        ))?;
                        let parts: Vec<&str> = row.split_whitespace().collect();
                        type_data[i].name = parts[1].to_string();
                        type_data[i].mass = parts[3].parse::<f64>().map_err(|e| {
                            ChimesError::InvalidFormat(format!(
                                "Error parsing the particle mass: {e}"
                            ))
                        })?;
                    }
                }

                l if l.starts_with("ATOM PAIRS:") => {
                    pair_count = l
                        .trim_start_matches("ATOM PAIRS: ")
                        .parse::<usize>()
                        .map_err(|e| {
                            ChimesError::InvalidFormat(format!(
                                "Error parsing the number of pair types: {e}"
                            ))
                        })?;
                }

                l if l.starts_with("# PAIRIDX #") && !l.contains("# USEPOVR #") => {
                    let (data, style) = Self::parse_pair_metadata(&mut lines, pair_count)?;
                    pair_data = data;
                    xform_style = style;
                }

                l if l.starts_with("FCUT TYPE:") => {
                    let p: Vec<&str> = l
                        .trim_start_matches("FCUT TYPE: ")
                        .split_whitespace()
                        .collect();
                    let fcut_style = p[0].to_string();
                    if fcut_style != "CUBIC" && fcut_style != "TERSOFF" {
                        return Err(ChimesError::InvalidFormat(format!("Unknown FCUT TYPE")).into());
                    }
                    fcut.0 = fcut_style;
                    if p.len() > 1 {
                        fcut.1 = Some(p[1].parse().map_err(|e| {
                            ChimesError::InvalidFormat(format!("Error parsing the Tersoff fo: {e}"))
                        })?);
                    }
                }

                l if l.starts_with("PAIR CHEBYSHEV PENALTY DIST:") => {
                    penalty_dist = l
                        .trim_start_matches("PAIR CHEBYSHEV PENALTY DIST: ")
                        .parse()
                        .map_err(|e| {
                            ChimesError::InvalidFormat(format!(
                                "Error parsing the penalty kick-in distance: {e}"
                            ))
                        })?;
                }

                l if l.starts_with("PAIR CHEBYSHEV PENALTY SCALING:") => {
                    penalty_scaling = l
                        .trim_start_matches("PAIR CHEBYSHEV PENALTY SCALING: ")
                        .parse()
                        .map_err(|e| {
                            ChimesError::InvalidFormat(format!(
                                "Error parsing the penalty scaling: {e}"
                            ))
                        })?;
                }

                l if l.starts_with("NO ENERGY OFFSETS:") => {
                    let n_energy_offset_line: Vec<&str> = line
                        .trim_start_matches("NO ENERGY OFFSETS: ")
                        .split_whitespace()
                        .collect();
                    let n_offset = n_energy_offset_line[0].parse::<usize>().map_err(|e| {
                        ChimesError::InvalidFormat(format!(
                            "Error parsing the number of energy offsets: {e}"
                        ))
                    })?;
                    if n_offset != atom_count {
                        return Err(ChimesError::InvalidFormat(format!(
                            "ERROR: Number of energy offsets do not match number of atom types"
                        ))
                        .into());
                    }
                    for i in 0..atom_count {
                        let row = lines
                            .next()
                            .ok_or(ChimesError::UnexpectedEof("Offsets".into()))?;
                        type_data[i].energy_offset = row
                            .split_whitespace()
                            .nth(3)
                            .unwrap()
                            .parse()
                            .map_err(|e| {
                                ChimesError::InvalidFormat(format!(
                                    "Error parsing the energy offsets: {e}"
                                ))
                            })?;
                    }
                }

                l if l.starts_with("PAIRTYPE PARAMS:") => {
                    let mut coeffs = Vec::with_capacity(N);
                    let pair_params_line: Vec<&str> = line
                        .trim_start_matches("PAIRTYPE PARAMS:")
                        .split_whitespace()
                        .collect();
                    let pair_idx = pair_params_line[0].parse::<usize>().map_err(|e| {
                        ChimesError::InvalidFormat(format!("Error parsing the pair index: {e}"))
                    })?;
                    for _ in 0..N {
                        let row = lines
                            .next()
                            .ok_or(ChimesError::UnexpectedEof("Do not find Coeffs".into()))?;
                        coeffs.push(Self::parse_f64_vec(row)?[1]);
                    }
                    pair_data[pair_idx].coeff = coeffs;
                }

                l if l.starts_with("PAIRMAPS: ") => {
                    let map_count = l
                        .trim_start_matches("PAIRMAPS: ")
                        .split_whitespace()
                        .next()
                        .unwrap()
                        .parse()
                        .map_err(|e| {
                            ChimesError::InvalidFormat(format!(
                                "Error parsing the number of pair maps: {e}"
                            ))
                        })?;
                    for _ in 0..map_count {
                        let row = lines
                            .next()
                            .ok_or(ChimesError::UnexpectedEof("Pair maps".into()))?;
                        let p: Vec<&str> = row.split_whitespace().collect();
                        pair_idx_slow_map.push(p[0].parse::<usize>().map_err(|e| {
                            ChimesError::InvalidFormat(format!(
                                "Error parsing the index of pair maps: {e}"
                            ))
                        })?);
                        pair_type_slow_map.push(p[1].to_string());
                    }
                }

                l if l.starts_with("SPECIAL 3B S_MINIM:") => {
                    let row: Vec<&str> = l
                        .trim_start_matches("SPECIAL 3B S_MINIM:")
                        .split_whitespace()
                        .collect();
                    let special_cutoffs_type = row[0].to_string();

                    if special_cutoffs_type == "ALL" {
                        triplet_special_r_in_status = TripletCutType::All;
                        triplet_special_r_in.push(vec![row[1].parse::<f64>().map_err(|e| {
                            ChimesError::InvalidFormat(format!(
                                "Error parsing the 3B special inner cutoff of ALL style: {e}"
                            ))
                        })?]);
                    } else if special_cutoffs_type == "SPECIFIC" {
                        let counts = row[1].parse::<usize>().map_err(|e| {
                            ChimesError::InvalidFormat(format!(
                                "Error reading numbers of specific inner cutoffs: {e}"
                            ))
                        })?;
                        triplet_special_r_in_status = TripletCutType::Specific;
                        let (cutoffs_pair_type, cutoffs) =
                            Self::parse_triplet_specific_cut(&mut lines, counts)?;
                        triplet_special_r_in_pair_type = cutoffs_pair_type;
                        triplet_special_r_in = cutoffs;
                    } else {
                        return Err(ChimesError::InvalidFormat(format!(
                            "Invalid special inner cutoff type. Found {}",
                            special_cutoffs_type
                        ))
                        .into());
                    }
                }

                l if l.starts_with("SPECIAL 3B S_MAXIM:") => {
                    let row: Vec<&str> = l
                        .trim_start_matches("SPECIAL 3B S_MAXIM:")
                        .split_whitespace()
                        .collect();
                    let special_cutoffs_type = row[0].to_string();

                    if special_cutoffs_type == "ALL" {
                        triplet_special_r_out_status = TripletCutType::All;
                        let cutoff = row[1].parse::<f64>().map_err(|e| {
                            ChimesError::InvalidFormat(format!(
                                "Error parsing the 3B special outer cutoff of ALL style: {e}"
                            ))
                        })?;
                        triplet_special_r_out.push(vec![cutoff]);
                    } else if special_cutoffs_type == "SPECIFIC" {
                        let counts = row[1].parse::<usize>().map_err(|e| {
                            ChimesError::InvalidFormat(format!(
                                "Error reading numbers of specific outer cutoffs: {e}"
                            ))
                        })?;
                        triplet_special_r_out_status = TripletCutType::Specific;
                        let (cutoffs_pair_type, cutoffs) =
                            Self::parse_triplet_specific_cut(&mut lines, counts)?;
                        triplet_special_r_out_pair_type = cutoffs_pair_type;
                        triplet_special_r_out = cutoffs;
                    } else {
                        return Err(ChimesError::InvalidFormat(format!(
                            "Invalid special outer cutoff type. Found {}",
                            special_cutoffs_type
                        ))
                        .into());
                    }
                }

                l if l.starts_with("TRIPLETTYPE PARAMS:") => {
                    if let Some(data) = Self::parse_triplet_params(&mut lines)? {
                        triplet_data.push(data);
                    }
                }

                l if l.starts_with("TRIPMAPS:") => {
                    let map_count = l
                        .trim_start_matches("TRIPMAPS: ")
                        .split_whitespace()
                        .next()
                        .unwrap()
                        .parse()
                        .map_err(|e| {
                            ChimesError::InvalidFormat(format!(
                                "Error parsing the number of triplet maps: {e}"
                            ))
                        })?;

                    for _ in 0..map_count {
                        let row = lines
                            .next()
                            .ok_or(ChimesError::UnexpectedEof("Triplet maps".into()))?;
                        let p: Vec<&str> = row.split_whitespace().collect();
                        triplet_idx_slow_map.push(p[0].parse::<usize>().map_err(|e| {
                            ChimesError::InvalidFormat(format!(
                                "Error parsing the index of triplet maps {e}"
                            ))
                        })?);
                        triplet_type_slow_map.push(p[1].to_string());
                    }
                }
                _ => {}
            }
        }
        // Final assembly of the two-body fast-lookup tables
        let (idx_map, type_map) = Self::build_fast_pair_maps(
            &type_data,
            &pair_data,
            &pair_idx_slow_map,
            &pair_type_slow_map,
        )?;
        let pair_idx_fast_map = idx_map;
        let pair_type_fast_map = type_map;

        if !triplet_data.is_empty() {
            // Final assembly of the three-body fast-lookup tables
            let triplet_idx_map = Self::build_fast_triplet_maps(
                &type_data,
                &pair_data,
                &pair_idx_slow_map,
                &pair_type_slow_map,
                &triplet_idx_slow_map,
                &triplet_type_slow_map,
            )?;
            triplet_idx_fast_map = triplet_idx_map;

            // Figure out three-body cutoffs
            let _ = Self::refine_triplet_cutoffs(
                &pair_data,
                &pair_idx_slow_map,
                &pair_type_slow_map,
                &triplet_special_r_in,
                &triplet_special_r_in_pair_type,
                &triplet_special_r_in_status,
                &triplet_special_r_out,
                &triplet_special_r_out_pair_type,
                &triplet_special_r_out_status,
                &triplet_idx_slow_map,
                &triplet_type_slow_map,
                &mut triplet_data,
            );
        }

        Ok(ChimesBuilder {
            poly_order,
            num_atom_types: atom_count,
            type_data,
            num_pair_types: pair_count,
            xform_style,
            pair_data,
            fcut,
            pair_idx_slow_map,
            pair_type_slow_map,
            pair_idx_fast_map,
            pair_type_fast_map,
            penalty_dist,
            penalty_scaling,
            triplet_data,
            triplet_idx_slow_map,
            triplet_type_slow_map,
            triplet_idx_fast_map,
        })
    }

    /// Assemble two-body `ChIMES` potential function given
    /// a `pair_idx`.
    ///
    /// # Errors
    ///
    /// Will return `Err` if the `pair_idx` provided
    /// do not exist in the parameter file.
    #[inline]
    pub fn get_twob_chimes_potential(
        &self,
        pair_idx: usize,
    ) -> Result<PairwiseCutoff<Isotropic<ChimesTwobPotential<N>>>, ChimesError> {
        if pair_idx >= self.pair_data.len() {
            return Err(ChimesError::Construction(format!(
                "Intend to access the potential model with pair idx {}, but only found {} pairs",
                pair_idx,
                self.pair_data.len()
            ))
            .into());
        }
        let transformatiom_fn = self.get_tranformation(pair_idx)?;
        let cheby2b: ChimesChebyshevExpansion<ChimesTransformation, N> =
            ChimesChebyshevExpansion::new(
                transformatiom_fn,
                self.pair_data[pair_idx].coeff.clone(),
                self.pair_data[pair_idx].r_in,
            );
        let chimes_2b_model = self.get_smoothing(cheby2b, pair_idx)?;
        let penalty_fn = ChimesPenalty {
            r_in: self.pair_data[pair_idx].r_in,
            a: self.penalty_scaling,
            dt: self.penalty_dist,
        };

        let chimes_potential = ChimesTwobPotential {
            type1: self.pair_data[pair_idx].type1.clone(),
            type2: self.pair_data[pair_idx].type2.clone(),
            chimes: chimes_2b_model,
            penalty: penalty_fn,
        };

        Ok(PairwiseCutoff(Isotropic {
            interaction: chimes_potential,
            r_cut: self.pair_data[pair_idx].r_out,
        }))
    }

    fn parse_pair_metadata<'a>(
        lines: &mut Peekable<impl Iterator<Item = &'a str>>,
        count: usize,
    ) -> Result<(Vec<PairTypeData>, String), ChimesError> {
        let mut pair_data = Vec::with_capacity(count);
        let mut consistent_style = String::new();

        for i in 0..count {
            let line = lines
                .next()
                .ok_or(ChimesError::UnexpectedEof(format!("Pair row {i}")))?;
            let parts: Vec<&str> = line.split_whitespace().collect();

            // Format detection: Indices based on standard ChIMES LSQ input specs.
            let (style_idx, morse_idx) = match parts.len() {
                8 => (6, 7),
                7 => (5, 6),
                _ => {
                    return Err(ChimesError::InvalidFormat(format!(
                        "Row {i} has {} columns (expected 7 or 8)",
                        parts.len()
                    ))
                    .into());
                }
            };

            let style = parts[style_idx].to_string();
            if i == 0 {
                consistent_style = style;
            } else if style != consistent_style {
                return Err(ChimesError::InvalidFormat(
                    "Mixed transformation styles not supported".into(),
                )
                .into());
            }

            let morse_lambda =
                if consistent_style == "MORSE" {
                    Some(parts[morse_idx].parse::<f64>().map_err(|_| {
                        ChimesError::InvalidFormat("Error reading mores lambda".into())
                    })?)
                } else {
                    None
                };
            
            // temporarily set coefficient to empty Vec
            pair_data.push(PairTypeData {
                type1: parts[1].to_string(),
                type2: parts[2].to_string(),
                r_in: parts[3].parse().map_err(|_| {
                    ChimesError::InvalidFormat("Error reading inner cutoffs".into())
                })?,
                r_out: parts[4].parse().map_err(|_| {
                    ChimesError::InvalidFormat("Error reading outer cutoffs".into())
                })?,
                morse_lambda,
                coeff: Vec::with_capacity(N),
            });
        }
        Ok((pair_data, consistent_style))
    }

    fn parse_triplet_params<'a>(
        lines: &mut Peekable<impl Iterator<Item = &'a str>>,
    ) -> Result<Option<TripletTypeData>, ChimesError> {
        // The header "TRIPLETTYPE PARAMS:" was already consumed in the match
        // Skip the index line
        let _ = lines
            .next()
            .ok_or(ChimesError::UnexpectedEof("Triplet index line".into()))?;

        // Read the line containing pair names and EXCLUDED status
        let info_line = lines
            .next()
            .ok_or(ChimesError::UnexpectedEof("Triplet info line".into()))?;
        let p: Vec<&str> = info_line.split_whitespace().collect();
        if p.len() < 5 {
            return Err(ChimesError::InvalidFormat(
                "Malformed triplet info line".into(),
            ));
        }

        // Check if this triplet is excluded from the potential
        if p[4] == "EXCLUDED:" {
            return Ok(None);
        }

        let triplet_pair_type = [p[1].to_string(), p[2].to_string(), p[3].to_string()];
        let n_coeffs = p[7]
            .parse::<usize>()
            .map_err(|e| ChimesError::InvalidFormat(format!("Invalid 3B term count: {e}")))?;

        // Skip the two header lines for the coefficient table
        for _ in 0..2 {
            lines
                .next()
                .ok_or(ChimesError::UnexpectedEof("3B coefficient headers".into()))?;
        }

        let mut powers = Vec::with_capacity(n_coeffs);
        let mut coeffs = Vec::with_capacity(n_coeffs);

        for _ in 0..n_coeffs {
            let row = lines
                .next()
                .ok_or(ChimesError::UnexpectedEof("3B coefficient row".into()))?;
            let p: Vec<&str> = row.split_whitespace().collect();
            if p.len() < 7 {
                return Err(ChimesError::InvalidFormat(
                    "Malformed 3B coefficient row".into(),
                ));
            }

            powers.push(vec![
                p[1].parse()
                    .map_err(|_| ChimesError::InvalidFormat("Invalid power".into()))?,
                p[2].parse()
                    .map_err(|_| ChimesError::InvalidFormat("Invalid power".into()))?,
                p[3].parse()
                    .map_err(|_| ChimesError::InvalidFormat("Invalid power".into()))?,
            ]);
            coeffs.push(
                p[6].parse()
                    .map_err(|_| ChimesError::InvalidFormat("Invalid coeff".into()))?,
            );
        }

        // temporarily set cutoffs to 0s
        Ok(Some(TripletTypeData {
            pair1: triplet_pair_type[0].clone(),
            pair2: triplet_pair_type[1].clone(),
            pair3: triplet_pair_type[2].clone(),
            r_in1: 0.0,
            r_in2: 0.0,
            r_in3: 0.0,
            r_out1: 0.0,
            r_out2: 0.0,
            r_out3: 0.0,
            powers,
            coeff: coeffs,
        }))
    }

    fn parse_triplet_specific_cut<'a>(
        lines: &mut Peekable<impl Iterator<Item = &'a str>>,
        counts: usize,
    ) -> Result<(Vec<Vec<String>>, Vec<Vec<f64>>), ChimesError> {
        let mut special_r_cut_pair_type = Vec::new();
        let mut special_r_cut = Vec::new();

        for _ in 0..counts {
            let row = lines
                .next()
                .ok_or(ChimesError::UnexpectedEof("Pair maps".into()))?;
            let p: Vec<&str> = row.split_whitespace().collect();
            special_r_cut_pair_type.push(vec![
                p[1].to_string(),
                p[2].to_string(),
                p[3].to_string(),
            ]);

            special_r_cut.push(vec![
                p[4].parse::<f64>().map_err(|_| {
                    ChimesError::InvalidFormat("Error reading specific cutoffs".into())
                })?,
                p[5].parse::<f64>().map_err(|_| {
                    ChimesError::InvalidFormat("Error reading specific cutoffs".into())
                })?,
                p[6].parse::<f64>().map_err(|_| {
                    ChimesError::InvalidFormat("Error reading specific cutoffs".into())
                })?,
            ]);
        }

        Ok((special_r_cut_pair_type, special_r_cut))
    }

    /// Use an efficient HashMap lookup for fast-mapping.
    fn build_fast_pair_maps(
        atoms: &[ParticleTypeData],
        pairs: &[PairTypeData],
        slow_idx_map: &[usize],
        slow_type_map: &[String],
    ) -> Result<(Vec<usize>, Vec<String>), ChimesError> {
        let mut idx_fast = Vec::with_capacity(atoms.len() * atoms.len());
        let mut type_fast = Vec::with_capacity(atoms.len() * atoms.len());
        let mapping: HashMap<&str, usize> = slow_idx_map
            .iter()
            .zip(slow_type_map.iter())
            .map(|(i, s)| (s.as_str(), *i))
            .collect();

        for a_i in atoms {
            for a_j in atoms {
                // 1. Resolve the pair index from the slow map
                let key = format!("{}{}", a_i.name, a_j.name);
                let idx = mapping.get(key.as_str()).ok_or_else(|| {
                    ChimesError::InvalidFormat(format!("Missing pair map for {key}"))
                })?;
                idx_fast.push(*idx);

                // 2. Resolve the original pair definition name (order-independent)
                let pair_def = pairs
                    .iter()
                    .find(|p| {
                        (a_i.name == p.type1 && a_j.name == p.type2)
                            || (a_j.name == p.type1 && a_i.name == p.type2)
                    })
                    .ok_or_else(|| {
                        ChimesError::InvalidFormat(format!(
                            "No pair parameters for {}/{}",
                            a_i.name, a_j.name
                        ))
                    })?;

                type_fast.push(format!("{}{}", pair_def.type1, pair_def.type2));
            }
        }
        Ok((idx_fast, type_fast))
    }

    fn build_fast_triplet_maps(
        atoms: &[ParticleTypeData],
        pair_data: &[PairTypeData],
        pair_idx_slow_map: &[usize],
        pair_type_slow_map: &[String],
        triplet_idx_slow_map: &[usize],
        triplet_type_slow_map: &[String],
    ) -> Result<Vec<usize>, ChimesError> {
        let mut idx_fast = Vec::new();
        let pair_mapping: HashMap<&str, usize> = pair_idx_slow_map
            .iter()
            .zip(pair_type_slow_map.iter())
            .map(|(i, s)| (s.as_str(), *i))
            .collect();
        let triplet_mapping: HashMap<&str, usize> = triplet_idx_slow_map
            .iter()
            .zip(triplet_type_slow_map.iter())
            .map(|(i, s)| (s.as_str(), *i))
            .collect();

        for atom_i in atoms {
            for atom_j in atoms {
                for atom_k in atoms {
                    // 1. Resolve the pair index from the slow map
                    let key_ij = format!("{}{}", atom_i.name, atom_j.name);
                    let key_ik = format!("{}{}", atom_i.name, atom_k.name);
                    let key_jk = format!("{}{}", atom_j.name, atom_k.name);

                    let pair_idx_ij = pair_mapping.get(key_ij.as_str()).ok_or_else(|| {
                        ChimesError::InvalidFormat(format!("Missing pair map for ij: {key_ij}"))
                    })?;
                    let pair_idx_ik = pair_mapping.get(key_ik.as_str()).ok_or_else(|| {
                        ChimesError::InvalidFormat(format!("Missing pair map for ik:{key_ik}"))
                    })?;
                    let pair_idx_jk = pair_mapping.get(key_jk.as_str()).ok_or_else(|| {
                        ChimesError::InvalidFormat(format!("Missing pair map for jk:{key_jk}"))
                    })?;

                    let proper_key_ij = format!(
                        "{}{}",
                        pair_data[*pair_idx_ij].type1, pair_data[*pair_idx_ij].type2
                    );
                    let proper_key_ik = format!(
                        "{}{}",
                        pair_data[*pair_idx_ik].type1, pair_data[*pair_idx_ik].type2
                    );
                    let proper_key_jk = format!(
                        "{}{}",
                        pair_data[*pair_idx_jk].type1, pair_data[*pair_idx_jk].type2
                    );

                    let triplet_key =
                        format!("{}{}{}", proper_key_ij, proper_key_ik, proper_key_jk);

                    let idx = triplet_mapping.get(triplet_key.as_str()).ok_or_else(|| {
                        ChimesError::InvalidFormat(format!("Missing triplet map for {triplet_key}"))
                    })?;
                    idx_fast.push(*idx);
                }
            }
        }
        Ok(idx_fast)
    }

    fn refine_triplet_cutoffs(
        pair_data: &[PairTypeData],
        pair_idx_slow_map: &Vec<usize>,
        pair_type_slow_map: &Vec<String>,
        triplet_special_r_in: &Vec<Vec<f64>>,
        triplet_special_r_in_pair_type: &Vec<Vec<String>>,
        triplet_special_r_in_status: &TripletCutType,
        triplet_special_r_out: &Vec<Vec<f64>>,
        triplet_special_r_out_pair_type: &Vec<Vec<String>>,
        triplet_special_r_out_status: &TripletCutType,
        triplet_idx_slow_map: &Vec<usize>,
        triplet_type_slow_map: &Vec<String>,
        triplet_data: &mut Vec<TripletTypeData>,
    ) -> Result<(), ChimesError> {
        let pair_mapping: HashMap<&str, usize> = pair_idx_slow_map
            .iter()
            .zip(pair_type_slow_map.iter())
            .map(|(i, s)| (s.as_str(), *i))
            .collect();
        let triplet_mapping: HashMap<&str, usize> = triplet_idx_slow_map
            .iter()
            .zip(triplet_type_slow_map.iter())
            .map(|(i, s)| (s.as_str(), *i))
            .collect();

        // Define the two passes: (status, special_values, special_types, is_inner)
        // Inner and outer cutoffs could have different styles
        let passes = [
            (
                triplet_special_r_in_status,
                triplet_special_r_in,
                triplet_special_r_in_pair_type,
                true,
            ),
            (
                triplet_special_r_out_status,
                triplet_special_r_out,
                triplet_special_r_out_pair_type,
                false,
            ),
        ];

        for (status, spec_vals, spec_types, is_in) in passes {
            match status {
                TripletCutType::None => {
                    for tri in triplet_data.iter_mut() {
                        let c1 = pair_mapping.get(tri.pair1.as_str()).unwrap();
                        let c2 = pair_mapping.get(tri.pair2.as_str()).unwrap();
                        let c3 = pair_mapping.get(tri.pair3.as_str()).unwrap();
                        if is_in {
                            (tri.r_in1, tri.r_in2, tri.r_in3) = (
                                pair_data[*c1].r_in,
                                pair_data[*c2].r_in,
                                pair_data[*c3].r_in,
                            );
                        } else {
                            (tri.r_out1, tri.r_out2, tri.r_out3) = (
                                pair_data[*c1].r_out,
                                pair_data[*c2].r_out,
                                pair_data[*c3].r_out,
                            );
                        }
                    }
                }
                TripletCutType::All => {
                    let val = spec_vals[0][0];
                    for tri in triplet_data.iter_mut() {
                        if is_in {
                            (tri.r_in1, tri.r_in2, tri.r_in3) = (val, val, val);
                        } else {
                            (tri.r_out1, tri.r_out2, tri.r_out3) = (val, val, val);
                        }
                    }
                }
                TripletCutType::Specific => {
                    for (pair_type, cuts) in spec_types.iter().zip(spec_vals.iter()) {
                        let key = format!("{}{}{}", pair_type[0], pair_type[1], pair_type[2]);
                        let tri_idx = triplet_mapping.get(key.as_str()).ok_or_else(|| {
                            ChimesError::InvalidFormat(format!("Missing triplet map: {key}"))
                        })?;
                        let tri = &mut triplet_data[*tri_idx];

                        // Match specific pairs to their correct slots (1, 2, or 3)
                        for i in 0..3 {
                            if pair_type[i] == tri.pair1 {
                                if is_in {
                                    tri.r_in1 = cuts[i]
                                } else {
                                    tri.r_out1 = cuts[i]
                                }
                            }
                            if pair_type[i] == tri.pair2 {
                                if is_in {
                                    tri.r_in2 = cuts[i]
                                } else {
                                    tri.r_out2 = cuts[i]
                                }
                            }
                            if pair_type[i] == tri.pair3 {
                                if is_in {
                                    tri.r_in3 = cuts[i]
                                } else {
                                    tri.r_out3 = cuts[i]
                                }
                            }
                        }
                    }
                }
            }
        }

        Ok(())
    }

    /// Assemble transformation function.
    fn get_tranformation(&self, pair_idx: usize) -> Result<ChimesTransformation, ChimesError> {
        match self.xform_style.as_str() {
            "MORSE" => Ok(ChimesTransformation::Morse(MorseTransformation {
                lambda: self.pair_data[pair_idx]
                    .morse_lambda
                    .expect("Error reading morse lambda"),
                r_in: self.pair_data[pair_idx].r_in,
                r_out: self.pair_data[pair_idx].r_out,
            })),
            "INVERSE" => Ok(ChimesTransformation::Inverse(InverseTransformation {
                r_in: self.pair_data[pair_idx].r_in,
                r_out: self.pair_data[pair_idx].r_out,
            })),
            "DIRECT" => Ok(ChimesTransformation::Direct(DirectTransformation {
                r_in: self.pair_data[pair_idx].r_in,
                r_out: self.pair_data[pair_idx].r_out,
            })),
            _ => Err(ChimesError::Construction(format!(
                "Unknown transformation style: {}",
                self.xform_style
            ))
            .into()),
        }
    }

    /// Assemble smoothing function.
    fn get_smoothing(
        &self,
        f: ChimesChebyshevExpansion<ChimesTransformation, N>,
        pair_idx: usize,
    ) -> Result<ChimesSmoothing<ChimesTransformation, N>, ChimesError> {
        match self.fcut.0.as_str() {
            "CUBIC" => Ok(ChimesSmoothing::Cubic(CubicSmooth {
                f,
                r_out: self.pair_data[pair_idx].r_out,
            })),
            "TERSOFF" => Ok(ChimesSmoothing::Tersoff(TersoffSmooth {
                f,
                r_out: self.pair_data[pair_idx].r_out,
                r_in: self.pair_data[pair_idx].r_in,
                fo: self.fcut.1.expect("Error reading tersoff fo"),
            })),
            _ => Err(ChimesError::Construction(format!(
                "Unknown smoothing style: {}",
                self.fcut.0
            ))
            .into()),
        }
    }
    /// Parses a space-separated line into a vector of i32.
    fn parse_i32_vec(line: &str) -> Result<Vec<i32>, ChimesError> {
        let values = line
            .split_whitespace()
            .map(|s| {
                s.parse::<i32>().map_err(|e| {
                    ChimesError::InvalidFormat(format!("Error parsing the line of integers {e}",))
                })
            })
            .collect::<Result<Vec<i32>, _>>()?;
        Ok(values)
    }

    /// Parses a space-separated line into a vector of f64.
    fn parse_f64_vec(line: &str) -> Result<Vec<f64>, ChimesError> {
        let values = line
            .split_whitespace()
            .map(|s| {
                s.parse::<f64>().map_err(|e| {
                    ChimesError::InvalidFormat(format!("Error parsing the line of floats {e}",))
                })
            })
            .collect::<Result<Vec<f64>, _>>()?;
        Ok(values)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rstest::*;

    #[rstest]
    #[should_panic(
        expected = "Failed to parse parameter file: UnexpectedEof(\"Error reading the parameter file: No such file or directory (os error 2)\")"
    )]
    fn invalid_file_name() {
        const N: usize = 1;
        const M: usize = 0;
        let mut file_path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        file_path.push("test-data");
        file_path.push("donotexist.txt");

        let _ = ChimesBuilder::<N, M>::parse(
            file_path.to_str().expect("Path contains invalid symbols"),
        )
        .expect("Failed to parse parameter file");
    }

    #[rstest]
    #[should_panic(
        expected = "Error assembling ChIMES potential: Construction(\"Intend to access the potential model with pair idx 1, but only found 1 pairs\")"
    )]
    fn invalid_pair_index() {
        const N: usize = 12;
        const M: usize = 0;
        let mut file_path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        file_path.push("test-data");
        file_path.push("C-twobody.txt");

        let params = ChimesBuilder::<N, M>::parse(
            file_path.to_str().expect("Path contains invalid symbols"),
        )
        .expect("Failed to parse parameter file");

        let _ = params
            .get_twob_chimes_potential(1)
            .expect("Error assembling ChIMES potential");
    }

    #[rstest]
    #[should_panic(
        expected = "Failed to parse parameter file: InvalidFormat(\"Expected two-body order 8\")"
    )]
    fn mismatch_2b_order() {
        const N: usize = 8;
        const M: usize = 0;
        let mut file_path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        file_path.push("test-data");
        file_path.push("C-twobody.txt");

        let _ = ChimesBuilder::<N, M>::parse(
            file_path.to_str().expect("Path contains invalid symbols"),
        )
        .expect("Failed to parse parameter file");
    }

    #[rstest]
    #[should_panic(
        expected = "Failed to parse parameter file: InvalidFormat(\"Expected three-body order 1\")"
    )]
    fn mismatch_3b_order() {
        const N: usize = 12;
        const M: usize = 1;
        let mut file_path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        file_path.push("test-data");
        file_path.push("C-twobody.txt");

        let _ = ChimesBuilder::<N, M>::parse(
            file_path.to_str().expect("Path contains invalid symbols"),
        )
        .expect("Failed to parse parameter file");
    }

    #[rstest]
    fn parse_c_2b() {
        const N: usize = 12;
        const M: usize = 0;

        let mut file_path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        file_path.push("test-data");
        file_path.push("C-twobody.txt");

        // Read the entire file content into a String
        // This returns a Result, so we use `?` to propagate any errors
        let params = ChimesBuilder::<N, M>::parse(
            file_path.to_str().expect("Path contains invalid symbols"),
        )
        .expect("Failed to parse parameter file");

        let expected_poly_order = vec![N, M, 0];
        let expected_type_data = vec![ParticleTypeData {
            name: String::from("C"),
            mass: 12.011,
            energy_offset: 0.0,
        }];
        let expected_xform_style = String::from("MORSE");
        let expected_pair_data = vec![PairTypeData {
            type1: String::from("C"),
            type2: String::from("C"),
            r_in: 1.0,
            r_out: 3.15,
            morse_lambda: Some(1.25),
            coeff: vec![
                285.738_833_080_72,
                -213.713_887_523_72,
                358.533_310_990_31,
                -172.124_004_865_49,
                44.775_023_503_15,
                -34.154_784_921_509,
                30.632_345_544_482,
                -33.336_059_893_072,
                11.483_163_813_684,
                -0.990_867_207_911_8,
                -3.383_013_890_418_8,
                1.248_010_862_845_3,
            ],
        }];
        let expected_fcut: (String, Option<f64>) = (String::from("CUBIC"), None);
        let expected_penalty_dist = 0.01;
        let expected_penalty_scaling = 1e+8;
        let expected_pair_idx_slow_map = vec![0];
        let expected_pair_type_slow_map = vec!["CC"];
        let expected_pair_idx_fast_map = vec![0];
        let expected_pair_type_fast_map = vec!["CC"];

        // 2b parts
        assert_eq!(params.poly_order, expected_poly_order);
        assert_eq!(params.type_data, expected_type_data);
        assert_eq!(params.xform_style, expected_xform_style);
        assert_eq!(params.pair_data, expected_pair_data);
        assert_eq!(params.fcut, expected_fcut);
        assert_eq!(params.penalty_dist, expected_penalty_dist);
        assert_eq!(params.penalty_scaling, expected_penalty_scaling);
        assert_eq!(params.pair_idx_slow_map, expected_pair_idx_slow_map);
        assert_eq!(params.pair_type_slow_map, expected_pair_type_slow_map);
        assert_eq!(params.pair_idx_fast_map, expected_pair_idx_fast_map);
        assert_eq!(params.pair_type_fast_map, expected_pair_type_fast_map);

        // empty triplet data
        assert_eq!(params.triplet_data, []);
        assert_eq!(params.triplet_idx_fast_map, []);

        // obtain potential function
        let chimes_pot = params
            .get_twob_chimes_potential(0)
            .expect("Error assembling ChIMES potential");
        assert_eq!(chimes_pot.0.interaction.type1, String::from("C"));
        assert_eq!(chimes_pot.0.interaction.type2, String::from("C"));
    }

    #[rstest]
    fn parse_hn3_3b_rout_all() {
        const N: usize = 12;
        const M: usize = 8;

        let mut file_path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        file_path.push("test-data");
        file_path.push("HN-fourbody.txt");

        let params = ChimesBuilder::<N, M>::parse(
            file_path.to_str().expect("Path contains invalid symbols"),
        )
        .expect("Failed to parse parameter file");

        let expected_poly_order = vec![N, M, 4];
        let expected_type_data = vec![
            ParticleTypeData {
                name: String::from("N"),
                mass: 14.0064,
                energy_offset: -126.828700616,
            },
            ParticleTypeData {
                name: String::from("H"),
                mass: 1.0079,
                energy_offset: -59.0402284083,
            },
        ];

        let expected_xform_style = String::from("MORSE");
        let expected_pair_data = vec![
            PairTypeData {
                type1: String::from("N"),
                type2: String::from("N"),
                r_in: 0.793,
                r_out: 8.0,
                morse_lambda: Some(1.15),
                coeff: vec![
                    17.341_009_355_697_139,
                    57.774_119_773_766_508,
                    76.220_068_702_688_152,
                    40.597_946_713_780_949,
                    -3.090_950_293_142_406_7,
                    -9.568_323_288_481_783_7,
                    -1.398_446_509_119_888_8,
                    -0.284_883_283_536_185_81,
                    -0.217_319_593_051_684_55,
                    0.156_890_951_659_628_66,
                    0.056_716_863_392_651_549,
                    0.214_859_981_309_824_75,
                ],
            },
            PairTypeData {
                type1: String::from("H"),
                type2: String::from("H"),
                r_in: 0.451,
                r_out: 8.0,
                morse_lambda: Some(0.8),
                coeff: vec![
                    12.505_788_696_001_36,
                    28.829_120_708_867_389,
                    24.295_927_978_434_74,
                    9.351_183_377_623_707_2,
                    0.809_540_068_944_617_27,
                    1.108_761_409_653_912_5,
                    2.308_831_039_570_009_6,
                    -0.171_536_478_297_497_44,
                    0.035_436_599_340_995_96,
                    0.501_230_272_711_822_86,
                    -0.056_263_800_428_875_528,
                    0.203_871_981_318_344_89,
                ],
            },
            PairTypeData {
                type1: String::from("N"),
                type2: String::from("H"),
                r_in: 0.666,
                r_out: 8.0,
                morse_lambda: Some(1.0),
                coeff: vec![
                    1.701_481_886_171_263_5,
                    10.542_458_855_813_658,
                    13.624_902_173_816_118,
                    -1.951_617_500_501_013_2,
                    -11.233_817_110_914_156,
                    -4.308_217_478_930_769_7,
                    -0.189_647_654_903_229_32,
                    -0.921_076_193_724_393_2,
                    -0.159_350_209_186_874_81,
                    0.267_439_675_848_717_86,
                    0.034_690_942_326_356_888,
                    0.002_082_396_054_432_101_4,
                ],
            },
        ];
        let expected_fcut: (String, Option<f64>) = (String::from("TERSOFF"), Some(0.5));
        let expected_penalty_dist = 0.02;
        let expected_penalty_scaling = 1e+6;
        let expected_pair_idx_slow_map = vec![1, 2, 2, 0];
        let expected_pair_type_slow_map = vec!["HH", "HN", "NH", "NN"];
        let expected_pair_idx_fast_map = vec![0, 2, 2, 1];
        let expected_pair_type_fast_map = vec!["NN", "NH", "NH", "HH"];

        // 2b parts
        assert_eq!(params.poly_order, expected_poly_order);
        assert_eq!(params.type_data, expected_type_data);
        assert_eq!(params.xform_style, expected_xform_style);
        assert_eq!(params.pair_data, expected_pair_data);
        assert_eq!(params.fcut, expected_fcut);
        assert_eq!(params.penalty_dist, expected_penalty_dist);
        assert_eq!(params.penalty_scaling, expected_penalty_scaling);
        assert_eq!(params.pair_idx_slow_map, expected_pair_idx_slow_map);
        assert_eq!(params.pair_type_slow_map, expected_pair_type_slow_map);
        assert_eq!(params.pair_idx_fast_map, expected_pair_idx_fast_map);
        assert_eq!(params.pair_type_fast_map, expected_pair_type_fast_map);

        // Use specific ALL style for triplets outer cutoffs
        for data in params.triplet_data.clone() {
            assert_eq!(data.r_out1, 5.0);
            assert_eq!(data.r_out2, 5.0);
            assert_eq!(data.r_out3, 5.0);
        }
        // 3b fast map
        // here, we have two pair types
        // i+j+k in a for loop when i,j,k=0..2
        assert_eq!(params.triplet_idx_fast_map, [0, 1, 1, 2, 1, 2, 2, 3]);

        // obtain potential function
        let nn_pot = params
            .get_twob_chimes_potential(0)
            .expect("Error assembling ChIMES potential");
        let nh_pot = params
            .get_twob_chimes_potential(1)
            .expect("Error assembling ChIMES potential");
        let hh_pot = params
            .get_twob_chimes_potential(2)
            .expect("Error assembling ChIMES potential");
        assert_eq!(nn_pot.0.interaction.type1, String::from("N"));
        assert_eq!(nn_pot.0.interaction.type2, String::from("N"));
        assert_eq!(nh_pot.0.interaction.type1, String::from("H"));
        assert_eq!(nh_pot.0.interaction.type2, String::from("H"));
        assert_eq!(hh_pot.0.interaction.type1, String::from("N"));
        assert_eq!(hh_pot.0.interaction.type2, String::from("H"));
    }

    #[rstest]
    fn parse_co_3b_rout_specific() {
        const N: usize = 12;
        const M: usize = 5;

        let mut file_path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        file_path.push("test-data");
        file_path.push("CO-threebody.txt");

        // Read the entire file content into a String
        // This returns a Result, so we use `?` to propagate any errors
        let params = ChimesBuilder::<N, M>::parse(
            file_path.to_str().expect("Path contains invalid symbols"),
        )
        .expect("Failed to parse parameter file");

        let expected_poly_order = vec![N, M, 0];
        let expected_type_data = vec![
            ParticleTypeData {
                name: String::from("C"),
                mass: 12.011,
                energy_offset: 0.0,
            },
            ParticleTypeData {
                name: String::from("O"),
                mass: 15.999,
                energy_offset: 0.0,
            },
        ];
        let expected_xform_style = String::from("MORSE");
        let expected_pair_data = vec![
            PairTypeData {
                type1: String::from("C"),
                type2: String::from("C"),
                r_in: 0.988,
                r_out: 8.0,
                morse_lambda: Some(1.35),
                coeff: vec![
                    72.844_139_410_028_077,
                    16.442_598_180_203_255,
                    63.234_747_572_779_298,
                    13.223_354_284_863_532,
                    13.887_978_253_525_741,
                    -10.297_608_189_732_124,
                    5.382_406_484_259_831_8,
                    -3.090_905_804_870_906_2,
                    3.105_587_243_812_394_1,
                    -2.151_651_448_319_881_9,
                    1.159_856_744_653_014_4,
                    -0.269_870_823_647_806_9,
                ],
            },
            PairTypeData {
                type1: String::from("O"),
                type2: String::from("O"),
                r_in: 0.911,
                r_out: 8.0,
                morse_lambda: Some(2.55),
                coeff: vec![
                    159.726_543_354_900_34,
                    7.679_613_048_412_051_1,
                    94.330_216_362_323_114,
                    -7.838_069_330_633_146_6,
                    50.091_378_038_336_33,
                    -2.562_948_205_186_330_6,
                    23.966_068_974_686_692,
                    -13.766_695_140_416_509,
                    6.307_843_040_593_773_8,
                    -4.896_117_544_730_756_8,
                    1.142_176_093_019_064_5,
                    -0.654_068_181_807_563_32,
                ],
            },
            PairTypeData {
                type1: String::from("C"),
                type2: String::from("O"),
                r_in: 0.876,
                r_out: 8.0,
                morse_lambda: Some(1.15),
                coeff: vec![
                    39.436_095_003_817_584,
                    44.683_658_018_538_58,
                    73.230_655_851_105_894,
                    31.851_480_403_867_836,
                    8.397_746_398_541_764_6,
                    -2.415_757_885_263_914_8,
                    2.276_263_828_924_223_6,
                    -1.056_721_699_459_082_2,
                    0.698_822_497_318_531_97,
                    -1.018_765_905_165_672_3,
                    0.509_563_898_600_702_28,
                    -0.169_071_083_808_681_52,
                ],
            },
        ];
        let expected_fcut: (String, Option<f64>) = (String::from("CUBIC"), None);
        let expected_penalty_dist = 0.01;
        let expected_penalty_scaling = 1e+4;
        let expected_pair_idx_slow_map = vec![0, 2, 2, 1];
        let expected_pair_type_slow_map = vec!["CC", "CO", "OC", "OO"];
        let expected_pair_idx_fast_map = vec![0, 2, 2, 1];
        let expected_pair_type_fast_map = vec!["CC", "CO", "CO", "OO"];

        // 2b parts
        assert_eq!(params.poly_order, expected_poly_order);
        assert_eq!(params.type_data, expected_type_data);
        assert_eq!(params.xform_style, expected_xform_style);
        assert_eq!(params.pair_data, expected_pair_data);
        assert_eq!(params.fcut, expected_fcut);
        assert_eq!(params.penalty_dist, expected_penalty_dist);
        assert_eq!(params.penalty_scaling, expected_penalty_scaling);
        assert_eq!(params.pair_idx_slow_map, expected_pair_idx_slow_map);
        assert_eq!(params.pair_type_slow_map, expected_pair_type_slow_map);
        assert_eq!(params.pair_idx_fast_map, expected_pair_idx_fast_map);
        assert_eq!(params.pair_type_fast_map, expected_pair_type_fast_map);

        // the triplet cutoffs
        // use SPECIFIC style for outer cutoffs
        // the inner cutoffs should be the same as 2b cutoffs
        // the outer cutoffs is specified in the parameter file
        let expected_triplet_types = [
            ["CC", "CC", "CC"],
            ["CC", "CO", "CO"],
            ["CO", "CO", "OO"],
            ["OO", "OO", "OO"],
        ];
        let expected_triplet_rins = [
            [
                expected_pair_data[0].r_in,
                expected_pair_data[0].r_in,
                expected_pair_data[0].r_in,
            ],
            [
                expected_pair_data[0].r_in,
                expected_pair_data[2].r_in,
                expected_pair_data[2].r_in,
            ],
            [
                expected_pair_data[2].r_in,
                expected_pair_data[2].r_in,
                expected_pair_data[1].r_in,
            ],
            [
                expected_pair_data[1].r_in,
                expected_pair_data[1].r_in,
                expected_pair_data[1].r_in,
            ],
        ];
        let expected_triplet_routs = [
            [4.4, 4.4, 4.4],
            [4.4, 4.0, 4.0],
            [4.0, 4.0, 6.5],
            [6.5, 6.5, 6.5],
        ];
        for i in 0..params.triplet_data.len() {
            assert_eq!(params.triplet_data[i].pair1, expected_triplet_types[i][0]);
            assert_eq!(params.triplet_data[i].pair2, expected_triplet_types[i][1]);
            assert_eq!(params.triplet_data[i].pair3, expected_triplet_types[i][2]);
            assert_eq!(params.triplet_data[i].r_in1, expected_triplet_rins[i][0]);
            assert_eq!(params.triplet_data[i].r_in2, expected_triplet_rins[i][1]);
            assert_eq!(params.triplet_data[i].r_in3, expected_triplet_rins[i][2]);
            assert_eq!(params.triplet_data[i].r_out1, expected_triplet_routs[i][0]);
            assert_eq!(params.triplet_data[i].r_out2, expected_triplet_routs[i][1]);
            assert_eq!(params.triplet_data[i].r_out3, expected_triplet_routs[i][2]);
        }

        // 3b fast map
        // here, we have two pair types
        // i+j+k in a for loop when i,j,k=0..2
        assert_eq!(params.triplet_idx_fast_map, [0, 1, 1, 2, 1, 2, 2, 3]);

        // obtain 2b potential function
        let cc_pot = params
            .get_twob_chimes_potential(0)
            .expect("Error assembling ChIMES potential");
        let oo_pot = params
            .get_twob_chimes_potential(1)
            .expect("Error assembling ChIMES potential");
        let co_pot = params
            .get_twob_chimes_potential(2)
            .expect("Error assembling ChIMES potential");
        assert_eq!(cc_pot.0.interaction.type1, String::from("C"));
        assert_eq!(cc_pot.0.interaction.type2, String::from("C"));
        assert_eq!(oo_pot.0.interaction.type1, String::from("O"));
        assert_eq!(oo_pot.0.interaction.type2, String::from("O"));
        assert_eq!(co_pot.0.interaction.type1, String::from("C"));
        assert_eq!(co_pot.0.interaction.type2, String::from("O"));
    }
}
