[package]
name = "hoomd-linalg"
categories.workspace = true
description = "Linear algebra library optimized for small matrixes."
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
hoomd-vector.workspace = true
num-traits = "0.2.19"

[lints]
workspace = true

[features]
default = []

[dev-dependencies]
faer = "0.22.6"
approx.workspace = true
divan.workspace = true
rand.workspace = true
rstest.workspace = true


[[bench]]
name = "linalg"
harness = false
