[package]
name = "hoomd-bevy"
categories.workspace = true
description = "Interfrace HOOMD with the bevy game engine."
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme = "hoomd-bevt/README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bevy.workspace = true
bevy_diagnostic.workspace = true
bevy_winit.workspace = true
itertools.workspace = true
hoomd-manifold.workspace = true
hoomd-microstate.workspace = true
hoomd-vector.workspace = true
libm = "0.2.11"
