[package]
name = "hoomd-bevy"
categories.workspace = true
description = "Interfrace HOOMD with the bevy game engine."
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bevy.workspace = true
bevy_diagnostic.workspace = true
bevy_winit.workspace = true
itertools.workspace = true
hoomd-microstate.workspace = true
hoomd-vector.workspace = true
web-time = "1.1.0"

# Work around failing build: https://github.com/bevyengine/bevy/issues/17699#issuecomment-2862717597
[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3.3", default-features = false, features = ["wasm_js"] }
