[package]
name = "hoomd-microstate"
categories.workspace = true
description = "Store and manage a system microstate."
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme = "hoomd-microstate/README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
hoomd-vector = { path = "../hoomd-vector" }
hoomd-random = { path = "../hoomd-random" }

[dev-dependencies]
divan = "0.1.14"
rstest = "0.23.0"
