[package]
name = "hoomd-microstate"
categories.workspace = true
description = "Store and manage a system microstate."
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
hoomd-manifold.workspace = true
hoomd-geometry.workspace = true
hoomd-vector.workspace = true
hoomd-utility.workspace = true
rand.workspace = true
libm = "0.2.11"
approx = "0.5.1"
thiserror.workspace = true
tinyvec.workspace = true

[dev-dependencies]
hoomd-vector = { features = ["approx"], workspace = true }
approx.workspace = true
anyhow.workspace = true
divan.workspace = true
rand.workspace = true
rstest.workspace = true
