[package]
name = "hoomd-geometry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Performant, general computational geometry methods in Rust."

[dependencies]
hoomd-vector.workspace = true
hoomd-linear-algebra.workspace = true
hoomd-utility.workspace = true
rand.workspace = true
itertools.workspace = true
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
approx.workspace = true
divan.workspace = true
rstest.workspace = true

[[bench]]
name = "overlaps"
harness = false
