[package]
name = "hoomd-geometry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Performant, general computational geometry methods in Rust."

[dependencies]
rand.workspace = true
itertools.workspace = true
serde.workspace = true
serde_with.workspace = true
thiserror.workspace = true
robust.workspace = true

hoomd-manifold.workspace = true
hoomd-vector.workspace = true
hoomd-linear-algebra.workspace = true
hoomd-utility.workspace = true

[lints]
workspace = true

[dev-dependencies]
anyhow.workspace = true
assert2.workspace = true
approxim.workspace = true
divan.workspace = true
rstest.workspace = true

[[bench]]
name = "overlaps"
harness = false

[[bench]]
name = "hyperbolic_overlaps"
harness = false
