[package]
name = "hoomd-chimes"
categories.workspace = true
description = "ChIMES interatomic potential related implementation"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme = "hoomd-chimes/README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
hoomd-interaction.workspace = true
hoomd-geometry.workspace = true
hoomd-mc.workspace = true
hoomd-microstate.workspace = true
hoomd-simulation.workspace = true
hoomd-gsd.workspace = true
hoomd-spatial.workspace = true
hoomd-vector.workspace = true
hoomd-bevy.workspace=true
anyhow.workspace = true
arrayvec.workspace = true
bevy_egui.workspace = true
rand.workspace = true

[dev-dependencies]
bevy = { workspace = true }
approxim.workspace = true
divan.workspace = true
rstest.workspace = true

[[example]]
name = "TiO2-TiTi"
