[package]
name = "hoomd-rs-vector"
categories.workspace = true
description = "Vector and quaternion math library."
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme = "hoomd-rs-vector/README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
thiserror = "1.0.64"
rand = {version = "0.8.5", features=["min_const_gen"]}

[dev-dependencies]
divan = "0.1.14"
paste = "1.0.15"

[[bench]]
name = "cartesian"
harness = false
