[package]
name = "hoomd-rs-vector"
categories.workspace = true
description = "Vector and quaternion math library."
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme = "hoomd-rs-vector/README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
thiserror = "1.0.64"
rand = "0.8.5"

[dev-dependencies]
approx = "0.5.1"
divan = "0.1.14"
paste = "1.0.15"
rstest = "0.23.0"

[[bench]]
name = "cartesian"
harness = false

[[bench]]
name = "angle"
harness = false

[[bench]]
name = "quaternion"
harness = false
