[package]
name = "rsph"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
num-complex.workspace = true

[dev-dependencies]
approxim.workspace = true
divan.workspace = true
rand.workspace = true
rstest.workspace = true
sphrs.workspace = true

[lints]
workspace = true

[[bench]]
name = "bench_rsph"
harness = false
