[package]
name = "hoomd-geom"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hoomd-vector = { path= "../hoomd-vector" }
rstest = "0.24.0"

[lints]
workspace = true
