name: Style

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
    - trunk

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  cargo-check-clippy:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - name: Configure Rust
      uses: dtolnay/rust-toolchain@0b1efabc08b657293548b77fb76cc02d26091c7e
      with:
        toolchain: 1.90.0
        targets: wasm32-unknown-unknown
        components: clippy
    - name: Cache
      uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
      with:
        key: ${{ hashFiles('Cargo.lock') }}
        cache-bin: false

    # Unfortunately, it is not currently possible to mark warnings as errors with cargo check:
    # https://github.com/rust-lang/cargo/issues/8424#issuecomment-1915265827
    # The workaround does not work for hoomd-rs because we set rust configuration options.
    #
    # Check all targets in debug and release modes
    - name: cargo check [native]
      run: >
        cargo check
        --profile ci
        --locked
        --workspace
        --all-targets
        --all-features

    - name: cargo clippy [native]
      run: >
        cargo clippy
        --profile ci
        --locked
        --workspace
        --all-targets
        --all-features
        -- -Dwarnings

    # Check the examples in wasm builds with and without webgpu
    - name: cargo check [wasm32, features="bevy"]
      run: >
        cargo check
        --profile ci
        --features "bevy"
        --locked
        --workspace
        --lib
        --examples
        --target wasm32-unknown-unknown
    - name: cargo check [wasm32, features="bevy,webgpu"]
      run: >
        cargo check
        --profile ci
        --features "bevy,webgpu"
        --locked
        --workspace
        --lib
        --examples
        --target wasm32-unknown-unknown

    - name: cargo clippy [wasm32, features="bevy"]
      run: >
        cargo clippy
        --profile ci
        --features "bevy"
        --locked
        --workspace
        --lib
        --examples
        --target wasm32-unknown-unknown
        -- -Dwarnings
    - name: cargo clippy [wasm32, features="bevy,webgpu"]
      run: >
        cargo clippy
        --profile ci
        --features "bevy,webgpu"
        --locked
        --workspace
        --lib
        --examples
        --target wasm32-unknown-unknown
        -- -Dwarnings

  cargo-fmt:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - name: Configure Rust
      uses: dtolnay/rust-toolchain@0b1efabc08b657293548b77fb76cc02d26091c7e
      with:
        toolchain: nightly-2025-09-17
        components: rustfmt
    - run: cargo +nightly-2025-09-17 fmt --all --check

  prek:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - name: prek
      uses: glotzerlab/workflows/prek@894d9678188a02b06560fdeb2b9ba98d016cd371 # 0.10.0

  # This job is used to provide a single requirement for branch merge conditions.
  tests_complete:
    name: All style checks
    if: always()
    needs: [cargo-check-clippy, cargo-fmt, prek]
    runs-on: ubuntu-24.04

    steps:
    - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
    - name: Done
      run: exit 0
